name: Continuous Integration

on:
  pull_request:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Compile and Test (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'
      - name: Print the go version
        run: go version
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -race -cover -coverprofile=coverage.out ./...
      - name: Print Coverage
        run: go tool cover -func=coverage.out
      - name: Generate Coverage Report
        run: go tool cover -html=coverage.out -o=coverage.html
        shell: bash
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{runner.os}}
          path: ./coverage.html

  lints:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'
      - name: Print the go version
        run: go version
      - name: Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  generate:
    name: Go Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'
      - name: Run Go Generate
        run: go generate ./...
      - name: Check for Outdated Generated Code
        run: git diff --exit-code HEAD

  workflow-times:
    name: Workflow Timings
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Time Reporter
        uses: Michael-F-Bryan/workflow-timer@v0.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jobs: |
            Compile and Test (ubuntu-latest)
            Compile and Test (macos-latest)
            Compile and Test (windows-latest)
          message: |
            Make sure you keep an eye on build times!

            The goal is to keep CI times under 5 minutes so developers can maintain a fast edit-compile-test cycle.


